name: Code Quality

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Code-Quality.yml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Code-Quality.yml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'Project.toml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    permissions: # needed to allow julia-actions/cache to delete old caches that it has created
      actions: write
      contents: read
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - 'lts'
        os:
          - 'ubuntu-latest'
        arch:
          - 'x64'
        group:
          - 'Code-Quality'

    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
