name: Documenter

on:
  push:
    branches:
      - 'main'
    tags: 
      - '*'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/documentation.yml'
      - 'src/**'
      - 'ext/**'
      - 'docs/**'
      - 'examples/**'
      - 'Project.toml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    permissions: # needed to allow julia-actions/cache to delete old caches that it has created
      actions: write
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          JULIA_DEBUG: "Documenter"
          DATADEPS_ALWAYS_ACCEPT: true
          GKSwstype: "100" # for Plots.jl plots (if you have them)
